name: Build and deploy ASP.NET Core app to Azure Web App
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
env:
  AZURE_WEBAPP_NAME: New1WebApp  # Set this to the name of your Azure Web App
  DOTNET_VERSION: '7.0.x'  # Set this to the .NET Core version to use
 
jobs:
  build-and-deploy:
    runs-on: windows-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
 
      - name: Restore dependencies
        run: dotnet restore Optevus.Ethnicity/Optevus.Ethnicity.csproj
 
      - name: Build the project
        run: dotnet build Optevus.Ethnicity/Optevus.Ethnicity.csproj --configuration Release
 
      - name: Publish the project
        run: dotnet publish Optevus.Ethnicity/Optevus.Ethnicity.csproj --configuration Release --output ${{ github.workspace }}/publish
 
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/publish
